name: Nightly CLI test for release-0.8

on:
  schedule:
    - cron: '08 1,13 * * *'

jobs:
  test-suite:
    uses: konveyor/kantra-cli-tests/.github/workflows/test-suite.yaml@release-0.8
    secrets: inherit
    with:
      tag: release-0.8
      tier: TIER0
